name: iOS Build Console

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-ios:
    name: Build Console iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create Super Simple iOS App
        run: |
          echo "Creating the simplest possible iOS app..."

          mkdir -p SimpleApp

          # Create the most minimal iOS app possible
          cat > SimpleApp/main.swift << 'EOF'
          import Foundation
          import UIKit

          class AppDelegate: UIResponder, UIApplicationDelegate {
              var window: UIWindow?

              func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

                  window = UIWindow(frame: UIScreen.main.bounds)
                  window?.backgroundColor = UIColor.systemBlue
                  window?.makeKeyAndVisible()

                  // Create a simple view controller
                  let viewController = UIViewController()
                  viewController.view.backgroundColor = UIColor.systemGreen

                  // Add a label
                  let label = UILabel()
                  label.text = "🎵💡 Sound to Light Therapy\n\nWorking iOS App!\n\nIf you see this, the build succeeded! 🎉"
                  label.textAlignment = .center
                  label.numberOfLines = 0
                  label.font = UIFont.systemFont(ofSize: 20, weight: .bold)
                  label.textColor = UIColor.white
                  label.translatesAutoresizingMaskIntoConstraints = false

                  viewController.view.addSubview(label)
                  NSLayoutConstraint.activate([
                      label.centerXAnchor.constraint(equalTo: viewController.view.centerXAnchor),
                      label.centerYAnchor.constraint(equalTo: viewController.view.centerYAnchor),
                      label.leadingAnchor.constraint(greaterThanOrEqualTo: viewController.view.leadingAnchor, constant: 20),
                      label.trailingAnchor.constraint(lessThanOrEqualTo: viewController.view.trailingAnchor, constant: -20)
                  ])

                  window?.rootViewController = viewController

                  print("🎵💡 Sound to Light Therapy - iOS App Started Successfully!")
                  return true
              }
          }

          @main
          class Application {
              static func main() {
                  UIApplicationMain(
                      CommandLine.argc,
                      CommandLine.unsafeArgv,
                      nil,
                      NSStringFromClass(AppDelegate.self)
                  )
              }
          }
          EOF

      - name: Build iOS App
        run: |
          echo "Building simple iOS app..."

          # Get iOS SDK
          IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          echo "Using iOS SDK: $IOS_SDK"

          # Create app bundle
          mkdir -p build/SoundToLightApp.app

          # Compile with minimal frameworks
          xcrun --sdk iphoneos swiftc \
            -target arm64-apple-ios15.0 \
            -sdk "$IOS_SDK" \
            -o build/SoundToLightApp.app/SoundToLightApp \
            SimpleApp/main.swift \
            -framework Foundation \
            -framework UIKit

          echo "✅ Simple iOS app compiled!"

          # Check the binary
          file build/SoundToLightApp.app/SoundToLightApp
          ls -lh build/SoundToLightApp.app/SoundToLightApp

      - name: Create App Bundle
        run: |
          # Create minimal Info.plist
          cat > build/SoundToLightApp.app/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDisplayName</key>
              <string>Sound Light</string>
              <key>CFBundleExecutable</key>
              <string>SoundToLightApp</string>
              <key>CFBundleIdentifier</key>
              <string>com.test.soundlight</string>
              <key>CFBundleName</key>
              <string>SoundToLightApp</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
              <key>UISupportedInterfaceOrientations</key>
              <array>
                  <string>UIInterfaceOrientationPortrait</string>
              </array>
              <key>UIRequiredDeviceCapabilities</key>
              <array>
                  <string>armv7</string>
              </array>
          </dict>
          </plist>
          EOF

          chmod +x build/SoundToLightApp.app/SoundToLightApp

          echo "App bundle contents:"
          ls -la build/SoundToLightApp.app/

      - name: Create IPA
        run: |
          mkdir -p build/Payload
          cp -r build/SoundToLightApp.app build/Payload/

          cd build
          zip -r SoundToLightApp-Simple.ipa Payload/
          cd ..

          echo "✅ Simple iOS IPA created:"
          ls -la build/*.ipa

      - name: Upload Simple Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-simple-build
          path: |
            build/*.ipa
            build/SoundToLightApp.app/
          retention-days: 3
