name: iOS Build Device Fixed

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-ios:
    name: Build iOS App (Device Fixed)
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Environment
        run: |
          xcode-select --print-path
          xcodebuild -version
          swift --version
          xcrun --sdk iphoneos --show-sdk-path

      - name: Build iOS App with Direct Compilation
        run: |
          echo "Building iOS app with direct swiftc compilation..."

          # Get iOS SDK path
          IOS_SDK_PATH=$(xcrun --sdk iphoneos --show-sdk-path)
          echo "Using iOS SDK: $IOS_SDK_PATH"

          # Create build directory
          mkdir -p build/ios-device

          # Compile Swift files directly for iOS device
          echo "Compiling Swift files for iOS ARM64..."
          xcrun --sdk iphoneos swiftc \
            -target arm64-apple-ios17.0 \
            -sdk "$IOS_SDK_PATH" \
            -O \
            -module-name SoundToLightTherapyApp \
            -o build/ios-device/SoundToLightTherapyApp \
            Sources/SoundToLightTherapyApp/main.swift \
            $(find Sources/SoundToLightTherapy -name "*.swift" -type f | tr '\n' ' ') \
            -framework Foundation \
            -framework SwiftUI \
            -framework UIKit \
            -framework AVFoundation \
            -framework Accelerate \
            -Xlinker -rpath -Xlinker @executable_path/Frameworks \
            -Xlinker -rpath -Xlinker /System/Library/Frameworks

          echo "✅ iOS device compilation completed successfully"

          # Verify the binary
          echo "Binary info:"
          file build/ios-device/SoundToLightTherapyApp

          echo "Binary size:"
          ls -lh build/ios-device/SoundToLightTherapyApp

      - name: Create iOS App Bundle
        run: |
          echo "Creating iOS app bundle..."

          # Create app bundle directory
          APP_BUNDLE="build/SoundToLightTherapyApp.app"
          mkdir -p "$APP_BUNDLE"

          # Copy executable
          cp build/ios-device/SoundToLightTherapyApp "$APP_BUNDLE/"
          chmod +x "$APP_BUNDLE/SoundToLightTherapyApp"

          # Create Info.plist
          cat > "$APP_BUNDLE/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDisplayName</key>
    <string>Sound to Light Therapy</string>
    <key>CFBundleExecutable</key>
    <string>SoundToLightTherapyApp</string>
    <key>CFBundleIdentifier</key>
    <string>com.eggzy.soundtolighttherapy</string>
    <key>CFBundleName</key>
    <string>SoundToLightTherapyApp</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>4</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>This app uses the microphone to detect sound frequencies for therapeutic light synchronization.</string>
    <key>NSCameraUsageDescription</key>
    <string>This app uses the camera to control the flashlight for therapeutic light synchronization.</string>
    <key>UIViewControllerBasedStatusBarAppearance</key>
    <false/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>arm64</string>
    </array>
    <key>MinimumOSVersion</key>
    <string>17.0</string>
</dict>
</plist>
EOF

          echo "✅ App bundle created successfully"
          ls -la "$APP_BUNDLE/"

      - name: Create IPA
        run: |
          echo "Creating iOS IPA..."

          mkdir -p build/Payload
          cp -r build/SoundToLightTherapyApp.app build/Payload/

          cd build
          zip -r SoundToLightTherapyApp-iOS-Device-Fixed.ipa Payload/
          cd ..

          echo "✅ iOS device IPA created:"
          ls -la build/*.ipa

      - name: Upload iOS Device Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-device-build-fixed
          path: |
            build/*.ipa
            build/SoundToLightTherapyApp.app/
          retention-days: 7
