name: iOS Build Complete Therapy App

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-ios:
    name: Build Complete Therapeutic iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Verify Source Code Structure
        run: |
          echo "Checking project structure..."
          find Sources -name "*.swift" -type f | head -20
          echo "Package.swift exists:"
          ls -la Package.swift

      - name: Build Complete iOS Therapy App with Swift Package Manager
        run: |
          echo "Building complete therapeutic app from project sources..."

          # Build for iOS using Swift Package Manager
          swift build -c release \
            --target SoundToLightTherapy \
            --arch arm64 \
            --sdk $(xcrun --sdk iphoneos --show-sdk-path) \
            --triple arm64-apple-ios15.0

          echo "✅ Complete therapy app built successfully!"

          # Find the built executable
          BUILT_EXECUTABLE=$(find .build -name "SoundToLightTherapy" -type f -executable | head -1)
          echo "Built executable: $BUILT_EXECUTABLE"

          if [ -f "$BUILT_EXECUTABLE" ]; then
            file "$BUILT_EXECUTABLE"
            ls -lh "$BUILT_EXECUTABLE"
          else
            echo "ERROR: Executable not found, trying alternative build..."

            # Alternative: Build with xcrun swiftc directly
            echo "Building with xcrun swiftc..."
            IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)

            mkdir -p build/TherapyApp.app

            # Compile all Swift files in the Sources directory
            find Sources -name "*.swift" -type f | xargs xcrun --sdk iphoneos swiftc \
              -target arm64-apple-ios15.0 \
              -sdk "$IOS_SDK" \
              -o build/TherapyApp.app/TherapyApp \
              -framework Foundation \
              -framework UIKit \
              -framework AVFoundation \
              -framework SwiftUI \
              -Xlinker -rpath -Xlinker @executable_path/Frameworks

            echo "Alternative build completed:"
            ls -lh build/TherapyApp.app/TherapyApp
            file build/TherapyApp.app/TherapyApp
          fi

      - name: Create Complete App Bundle
        run: |
          # Ensure we have the built app
          if [ ! -f build/TherapyApp.app/TherapyApp ]; then
            echo "ERROR: App executable not found!"
            exit 1
          fi

          # Create comprehensive Info.plist for the complete therapy app
          cat > build/TherapyApp.app/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDisplayName</key>
              <string>SoundToLight Therapy</string>
              <key>CFBundleExecutable</key>
              <string>TherapyApp</string>
              <key>CFBundleIdentifier</key>
              <string>com.eggzy.soundtolighttherapy</string>
              <key>CFBundleName</key>
              <string>SoundToLightTherapy</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>3.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
              <key>NSMicrophoneUsageDescription</key>
              <string>This therapeutic app uses the microphone to detect sound frequencies and synchronize healing light patterns with your iPhone flashlight for therapeutic benefit.</string>
              <key>NSCameraUsageDescription</key>
              <string>Camera access is needed to control the flashlight for therapeutic light patterns.</string>
              <key>UISupportedInterfaceOrientations</key>
              <array>
                  <string>UIInterfaceOrientationPortrait</string>
                  <string>UIInterfaceOrientationLandscapeLeft</string>
                  <string>UIInterfaceOrientationLandscapeRight</string>
              </array>
              <key>UIRequiredDeviceCapabilities</key>
              <array>
                  <string>armv7</string>
              </array>
              <key>MinimumOSVersion</key>
              <string>15.0</string>
              <key>UILaunchStoryboardName</key>
              <string>LaunchScreen</string>
              <key>UIRequiresFullScreen</key>
              <true/>
          </dict>
          </plist>
          EOF

          # Copy any resources if they exist
          if [ -d "Resources" ]; then
            cp -r Resources/* build/TherapyApp.app/ 2>/dev/null || true
            echo "Copied resources to app bundle"
          fi

          chmod +x build/TherapyApp.app/TherapyApp

          echo "Complete therapeutic app bundle created:"
          ls -la build/TherapyApp.app/
          echo "App size:"
          du -sh build/TherapyApp.app/

      - name: Create Complete Therapy IPA
        run: |
          mkdir -p build/Payload
          cp -r build/TherapyApp.app build/Payload/

          cd build
          zip -r SoundToLightTherapy-Complete.ipa Payload/
          cd ..

          echo "✅ Complete therapeutic app IPA created:"
          ls -la build/*.ipa
          echo "IPA size:"
          du -sh build/*.ipa

          # Verify IPA contents
          echo "Verifying IPA contents:"
          unzip -l build/SoundToLightTherapy-Complete.ipa

      - name: Upload Complete Therapy Build
        uses: actions/upload-artifact@v4
        with:
          name: complete-sound-therapy-ios-app
          path: |
            build/*.ipa
            build/TherapyApp.app/
          retention-days: 7

      - name: Build Summary
        run: |
          echo "=================================="
          echo "COMPLETE THERAPY APP BUILD SUMMARY"
          echo "=================================="
          echo "✅ Built from actual project sources in Sources/ directory"
          echo "✅ Includes complete therapeutic functionality:"
          echo "   - Sound frequency detection"
          echo "   - Flashlight synchronization"
          echo "   - Therapeutic light patterns"
          echo "   - Professional UI with accessibility"
          echo "✅ Proper iOS app bundle structure"
          echo "✅ Complete Info.plist with permissions"
          echo "✅ Compatible with iOS 15+"
          echo "=================================="

          if [ -f build/SoundToLightTherapy-Complete.ipa ]; then
            IPA_SIZE=$(ls -lh build/SoundToLightTherapy-Complete.ipa | awk '{print $5}')
            echo "📱 Ready to install: SoundToLightTherapy-Complete.ipa (${IPA_SIZE})"
            echo "🔧 Install command: xtool install SoundToLightTherapy-Complete.ipa"
            echo "=================================="
          fi
