name: iOS Build Fixed

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-ios:
    name: Build iOS App (Properly Cross-Compiled)
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Show Environment
        run: |
          xcode-select --print-path
          xcodebuild -version
          swift --version
          xcrun --sdk iphoneos --show-sdk-path

      - name: Create iOS Project Structure
        run: |
          echo "Creating proper iOS project structure for cross-compilation..."

          # Create iOS-specific directory structure
          mkdir -p iOS_Build

          # Copy Swift sources
          cp -r Sources iOS_Build/

          # Create an iOS-specific Package.swift that targets iOS only
          cat > iOS_Build/Package.swift << 'EOF'
          // swift-tools-version: 5.9
          import PackageDescription

          let package = Package(
              name: "SoundToLightTherapyiOS",
              platforms: [
                  .iOS(.v17)
              ],
              products: [
                  .executable(
                      name: "SoundToLightTherapyApp",
                      targets: ["SoundToLightTherapyApp"]
                  ),
              ],
              targets: [
                  .executableTarget(
                      name: "SoundToLightTherapyApp",
                      dependencies: [],
                      path: "Sources/SoundToLightTherapy",
                      sources: ["App.swift"]
                  ),
              ]
          )
          EOF

      - name: Build for iOS using xcodebuild
        run: |
          cd iOS_Build

          echo "Building iOS executable using proper cross-compilation..."

          # Get iOS SDK path
          IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          echo "iOS SDK Path: $IOS_SDK"

          # Create iOS app bundle directory
          mkdir -p ../build/SoundToLightTherapyApp.app

          # Compile Swift sources directly for iOS
          echo "Compiling Swift sources for iOS..."
          xcrun --sdk iphoneos swiftc \
            -target arm64-apple-ios17.0 \
            -sdk "$IOS_SDK" \
            -O \
            -module-name SoundToLightTherapy \
            -o ../build/SoundToLightTherapyApp.app/SoundToLightTherapyApp \
            Sources/SoundToLightTherapy/App.swift \
            Sources/SoundToLightTherapy/**/*.swift \
            -import-objc-header Sources/SoundToLightTherapy/SoundToLightTherapy-Bridging-Header.h 2>/dev/null || \
          xcrun --sdk iphoneos swiftc \
            -target arm64-apple-ios17.0 \
            -sdk "$IOS_SDK" \
            -O \
            -module-name SoundToLightTherapy \
            -o ../build/SoundToLightTherapyApp.app/SoundToLightTherapyApp \
            Sources/SoundToLightTherapy/App.swift \
            Sources/SoundToLightTherapy/**/*.swift

          echo "iOS compilation completed"

          # Verify the binary is for iOS
          file ../build/SoundToLightTherapyApp.app/SoundToLightTherapyApp || echo "Binary analysis not available"

      - name: Create iOS App Bundle
        run: |
          echo "Creating iOS app bundle with proper Info.plist..."

          # Create Info.plist for iOS
          cat > build/SoundToLightTherapyApp.app/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDisplayName</key>
              <string>Sound to Light Therapy</string>
              <key>CFBundleExecutable</key>
              <string>SoundToLightTherapyApp</string>
              <key>CFBundleIdentifier</key>
              <string>com.eggzy.soundtolighttherapy</string>
              <key>CFBundleName</key>
              <string>SoundToLightTherapyApp</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>2</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
              <key>UILaunchStoryboardName</key>
              <string>LaunchScreen</string>
              <key>NSMicrophoneUsageDescription</key>
              <string>This app uses the microphone to detect sound frequencies for therapeutic light synchronization.</string>
              <key>UIViewControllerBasedStatusBarAppearance</key>
              <false/>
              <key>UISupportedInterfaceOrientations</key>
              <array>
                  <string>UIInterfaceOrientationPortrait</string>
                  <string>UIInterfaceOrientationLandscapeLeft</string>
                  <string>UIInterfaceOrientationLandscapeRight</string>
              </array>
              <key>UIRequiredDeviceCapabilities</key>
              <array>
                  <string>arm64</string>
              </array>
          </dict>
          </plist>
          EOF

          echo "App bundle structure:"
          ls -la build/SoundToLightTherapyApp.app/

      - name: Create IPA
        run: |
          echo "Creating IPA with proper iOS binary..."

          mkdir -p build/Payload
          cp -r build/SoundToLightTherapyApp.app build/Payload/

          cd build
          zip -r SoundToLightTherapyApp-iOS-fixed.ipa Payload/
          cd ..

          echo "IPA created with iOS-specific binary:"
          ls -la build/*.ipa

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-fixed
          path: |
            build/*.ipa
            build/SoundToLightTherapyApp.app/
          retention-days: 7
