name: iOS Direct Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Direct iOS Compilation
        run: |
          # Create a simple iOS app bundle using direct swiftc compilation
          echo "🔨 Building iOS app with explicit iOS SDK targeting..."

          # Get iOS SDK
          IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          echo "Using iOS SDK: $IOS_SDK"

          # Create output directory
          mkdir -p build/ios-app

          # Compile for iOS device with explicit iOS linking
          echo "Compiling all Swift files for iOS device..."
          /usr/bin/xcrun -sdk iphoneos swiftc \
            -target arm64-apple-ios17.0 \
            -sdk "$IOS_SDK" \
            -Onone \
            -g \
            -module-name TherapyApp \
            -emit-executable \
            -o build/ios-app/TherapyApp \
            Sources/SoundToLightTherapyApp/main.swift \
            Sources/SoundToLightTherapy/Views/TherapyView.swift \
            Sources/SoundToLightTherapy/Managers/AudioCaptureManager.swift \
            Sources/SoundToLightTherapy/Managers/FlashlightController.swift \
            Sources/SoundToLightTherapy/Managers/FrequencyDetector.swift \
            Sources/SoundToLightTherapy/Managers/TherapySessionCoordinator.swift \
            Sources/SoundToLightTherapy/Utilities/DynamicTypeSupport.swift \
            Sources/SoundToLightTherapy/Utilities/HapticFeedbackSupport.swift \
            Sources/SoundToLightTherapy/Utilities/VoiceOverSupport.swift \
            Sources/SoundToLightTherapy/Utilities/ColorContrastSupport.swift \
            Sources/SoundToLightTherapy/Utilities/ReducedMotionSupport.swift \
            Sources/SoundToLightTherapy/Views/DynamicTypeTestView.swift \
            -import-objc-header /dev/null \
            -Xlinker -iOS_version_min -Xlinker 17.0 \
            -framework Foundation -framework UIKit -framework SwiftUI -framework AVFoundation -framework Accelerate

          echo "✅ iOS compilation completed"

          # Verify it's an iOS binary
          echo "Binary info:"
          file build/ios-app/TherapyApp

          # Create app bundle
          mkdir -p "build/TherapyApp.app"
          cp build/ios-app/TherapyApp "build/TherapyApp.app/"
          chmod +x "build/TherapyApp.app/TherapyApp"

          # Create Info.plist
          cat > "build/TherapyApp.app/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDisplayName</key>
    <string>Therapy App</string>
    <key>CFBundleExecutable</key>
    <string>TherapyApp</string>
    <key>CFBundleIdentifier</key>
    <string>com.eggzy.therapyapp</string>
    <key>CFBundleName</key>
    <string>TherapyApp</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>6</string>
    <key>LSRequiresIPhoneOS</key>
    <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>This app uses the microphone to detect sound frequencies for therapeutic light synchronization.</string>
    <key>NSCameraUsageDescription</key>
    <string>This app uses the camera to control the flashlight for therapeutic light synchronization.</string>
    <key>UIRequiredDeviceCapabilities</key>
    <array>
        <string>arm64</string>
    </array>
    <key>MinimumOSVersion</key>
    <string>17.0</string>
</dict>
</plist>
EOF

          # Create IPA
          mkdir -p build/Payload
          cp -r "build/TherapyApp.app" build/Payload/
          cd build
          zip -r TherapyApp-iOS-Direct.ipa Payload/
          cd ..

          echo "✅ Created iOS app bundle and IPA"
          ls -la build/*.ipa
          ls -la build/TherapyApp.app/

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-direct-build
          path: |
            build/*.ipa
            build/TherapyApp.app/
