name: iOS Build Minimal

on:
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-ios:
    name: Build Minimal iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create Minimal iOS App
        run: |
          echo "Creating minimal iOS app for testing..."

          # Create minimal working directory
          mkdir -p MinimalApp

          # Create a minimal SwiftUI app that should compile
          cat > MinimalApp/main.swift << 'EOF'
          import SwiftUI

          @main
          struct MinimalTherapyApp: App {
              var body: some Scene {
                  WindowGroup {
                      ContentView()
                  }
              }
          }

          struct ContentView: View {
              var body: some View {
                  VStack(spacing: 20) {
                      Text("🎵💡 Sound to Light Therapy")
                          .font(.title)
                          .multilineTextAlignment(.center)

                      Text("Minimal Test Version")
                          .font(.title2)
                          .foregroundColor(.blue)

                      Button("Test Button") {
                          print("Button tapped - app is working!")
                      }
                      .padding()
                      .background(Color.green)
                      .foregroundColor(.white)
                      .cornerRadius(8)

                      Text("If you see this, the iOS build is working! 🎉")
                          .font(.caption)
                          .foregroundColor(.secondary)
                          .padding()
                  }
                  .padding()
              }
          }
          EOF

      - name: Build Minimal iOS App
        run: |
          echo "Building minimal iOS app..."

          # Get iOS SDK path
          IOS_SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          echo "Using iOS SDK: $IOS_SDK"

          # Create app bundle
          mkdir -p build/MinimalTherapyApp.app

          # Compile minimal app
          xcrun --sdk iphoneos swiftc \
            -target arm64-apple-ios17.0 \
            -sdk "$IOS_SDK" \
            -o build/MinimalTherapyApp.app/MinimalTherapyApp \
            MinimalApp/main.swift \
            -framework SwiftUI \
            -framework Foundation \
            -framework UIKit

          echo "✅ Minimal iOS app compiled successfully!"

          # Verify binary
          file build/MinimalTherapyApp.app/MinimalTherapyApp

      - name: Create App Bundle
        run: |
          # Create Info.plist
          cat > build/MinimalTherapyApp.app/Info.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDisplayName</key>
              <string>Therapy Test</string>
              <key>CFBundleExecutable</key>
              <string>MinimalTherapyApp</string>
              <key>CFBundleIdentifier</key>
              <string>com.test.minimaltherapy</string>
              <key>CFBundleName</key>
              <string>MinimalTherapyApp</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
              <key>LSRequiresIPhoneOS</key>
              <true/>
              <key>UISupportedInterfaceOrientations</key>
              <array>
                  <string>UIInterfaceOrientationPortrait</string>
              </array>
              <key>UIRequiredDeviceCapabilities</key>
              <array>
                  <string>arm64</string>
              </array>
          </dict>
          </plist>
          EOF

          chmod +x build/MinimalTherapyApp.app/MinimalTherapyApp

          echo "App bundle created:"
          ls -la build/MinimalTherapyApp.app/

      - name: Create IPA
        run: |
          mkdir -p build/Payload
          cp -r build/MinimalTherapyApp.app build/Payload/

          cd build
          zip -r MinimalTherapyApp.ipa Payload/
          cd ..

          echo "✅ Minimal therapy app IPA created:"
          ls -la build/*.ipa

      - name: Upload Minimal Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-minimal-build
          path: |
            build/*.ipa
            build/MinimalTherapyApp.app/
          retention-days: 3
